### ISSUE TITLE
Cannot do the 'docker run' command in the course1 week1-lab on the path with space (Windows Users)

### ISSUE THREAD

**Issue by wanburana** [https-deeplearning-ai/MLEP-public#17]
I'm on Windows 10

I am trying to do the Method 2: Docker to do the lab
After I have successfully pulled the docker with `docker pull deeplearningai/mlepc1w1-ugl:jupyternb`. I then, proceed to run the second command  `docker run -it --rm -p 8888:8888 -p 8000:8000 --mount type=bind,source=$(pwd),target=/home/jovyan/work deeplearningai/mlepc1w1-ugl:jupyternb` 

I then get the error 
```
invalid argument "type=bind,source=C:/Users/msi/My" for "--mount" flag: target is required
See 'docker run --help'.
(mlep-w1-lab)
```

I suspected that my path is truncated (`C:/Users/msi/My`). What is the workaround here? How can I escape the space?

![image](https://user-images.githubusercontent.com/66191669/118172565-bb731280-b456-11eb-9e6d-ffb38896d6e1.png)

**Comment by risingape** [comment]
Hey,
the command should read 

`docker run -it --rm -p 8888:8888 -p 8000:8000 --mount type=bind,source="$(pwd)",target=/home/jovyan/work deeplearningai/mlepc1w1-ugl:jupyternb
`
This way it works on my Linux box.

Cheers

**Comment by andres-zartab** [comment]
@wanburana can you provide more context? Are you running the command within WSL2? From your screenshot I would guess so but the path you provided makes me think otherwise. If you are indeed within WSL2, it is recommended to host the files within the WSL2 filesystem. If you want to reference files in the Windows filesystem the path should be something like `/mnt/c/Users/YourUser`. 

If you are running it via cmd of Powershell after some research it looks that replacing `$(pwd)` with `%cd%` for cmd or `${PWD}` for Powershell should work. If you want to type in the path manually I think \ backslash should escape the space.

**Comment by wanburana** [comment]
> @wanburana can you provide more context? Are you running the command within WSL2? From your screenshot I would guess so but the path you provided makes me think otherwise. If you are indeed within WSL2, it is recommended to host the files within the WSL2 filesystem. If you want to reference files in the Windows filesystem the path should be something like `/mnt/c/Users/YourUser`.
> 
> If you are running it via cmd of Powershell after some research it looks that replacing `$(pwd)` with `%cd%` for cmd or `${PWD}` for Powershell should work. If you want to type in the path manually I think \ backslash should escape the space.

Thank you, I was using Docker for Desktop (Windows 10),  and I was running command using GIT Bash. so indeed I didn't run within WSL2. For some reason both of your solution didn't work for me. Maybe because I was running the command with GIT Bash instead of cmd or powershell. Nevertheless I was able to fix the problem with @risingape 's solution.

Cheers!

**Comment by wanburana** [comment]
> @wanburana can you provide more context? Are you running the command within WSL2? From your screenshot I would guess so but the path you provided makes me think otherwise. If you are indeed within WSL2, it is recommended to host the files within the WSL2 filesystem. If you want to reference files in the Windows filesystem the path should be something like `/mnt/c/Users/YourUser`.
> 
> If you are running it via cmd of Powershell after some research it looks that replacing `$(pwd)` with `%cd%` for cmd or `${PWD}` for Powershell should work. If you want to type in the path manually I think \ backslash should escape the space.

This one works! Thank you!

**Comment by andres-zartab** [comment]
Gonna leave this open in case it is useful for other learners.

**Comment by changyaochen** [comment]
> Hey,
> the command should read
> 
> `docker run -it --rm -p 8888:8888 -p 8000:8000 --mount type=bind,source="$(pwd)",target=/home/jovyan/work deeplearningai/mlepc1w1-ugl:jupyternb `
> This way it works on my Linux box.
> 
> Cheers

I was facing the same error, and this trick (adding double quotes surrounding `$(pwd)`) also solved my issue. I think the root cause is the white spaces in your path (`pwd`), and adding double quotes escapes the white spaces.

**Comment by dachosen1** [comment]
I'm getting another error from the docker file. Any ideas on how to fix this? 

![image](https://user-images.githubusercontent.com/40616129/119074448-eb18a200-b9a3-11eb-9bb2-74d9dc6cf4a7.png)

**Comment by andres-zartab** [comment]
> @wanburana can you provide more context? Are you running the command within WSL2? From your screenshot I would guess so but the path you provided makes me think otherwise. If you are indeed within WSL2, it is recommended to host the files within the WSL2 filesystem. If you want to reference files in the Windows filesystem the path should be something like `/mnt/c/Users/YourUser`.
> 
> If you are running it via cmd of Powershell after some research it looks that replacing `$(pwd)` with `%cd%` for cmd or `${PWD}` for Powershell should work. If you want to type in the path manually I think \ backslash should escape the space.

Have you tried the this?

**Comment by dachosen1** [comment]
> 
> 
> > @wanburana can you provide more context? Are you running the command within WSL2? From your screenshot I would guess so but the path you provided makes me think otherwise. If you are indeed within WSL2, it is recommended to host the files within the WSL2 filesystem. If you want to reference files in the Windows filesystem the path should be something like `/mnt/c/Users/YourUser`.
> > If you are running it via cmd of Powershell after some research it looks that replacing `$(pwd)` with `%cd%` for cmd or `${PWD}` for Powershell should work. If you want to type in the path manually I think \ backslash should escape the space.
> 
> @dachosen1 Have you tried this?

Yep I tried those. I'm using windows powershell. Where did I go wrong?

![image](https://user-images.githubusercontent.com/40616129/119213686-f0462180-ba75-11eb-841d-c435adb18d64.png)

**Comment by andres-zartab** [comment]
@dachosen1 I dont know if you already tested it but try using `${PWD}` (curly braces) instead of `$(PWD)`. If that doesn't work  you can try replacing the pwd command with the hardcoded path and make sure it is enclosed with double quotes. If the error persists I would suggest running the command from a WSL2 shell instead of Powershell.
