### ISSUE TITLE
Windows 10 (conda): no module named cv2

### ISSUE THREAD

**Issue by gsasikiran** [https-deeplearning-ai/MLEP-public#22]
When I activated the conda environment and ran jupyter lab, I got the following error while importing cv2
```
no module named cv2
```

**Fix:** Run ```python -m jupyterlab``` instead of ```jupyter lab``` in cmd.

**Reason:** When you run ```jupyter lab``` command, the path variables of jupyter lab are default system path variables. These differ from environment path variables. You can see this by importing sys and checking sys.path.

So ```python -m jupyterlab``` will open the jupyterlab with same path variables as environment path variables.

I would like you to update the README.md accordingly.

**Comment by andres-zartab** [comment]
Hi @gsasikiran, can you point out what OS are you using? For me in WSL2 this is not case and many learners have not faced this issue so I prefer to add a note to the readme for learners who do find this issue instead of changing the command for everyone. Thanks for reporting!

**Comment by gsasikiran** [comment]
Hello @andres-zartab. I am using default windows 10 with anaconda prompt! Sure I think note will work too.. incase some learners find the error.

**Comment by andres-zartab** [comment]
Added this to the Discourse topics for other learners to find. You can find it here: https://discourse.deeplearning.ai/t/no-module-named-cv2/17833

Thanks again! :)
