### ISSUE TITLE
error downloading yolo

### ISSUE THREAD

**Issue by anusha1110** [https-deeplearning-ai/MLEP-public#26]
while runing detect_and_draw_box() in part-1, It is throwing below error:

Downloading yolov3-tiny.cfg from https://github.com/pjreddie/darknet/raw/master/cfg/yolov3-tiny.cfg
Could not establish connection. Download failed
Downloading yolov3_classes.txt from https://github.com/arunponnusamy/object-detection-opencv/raw/master/yolov3.txt
Could not establish connection. Download failed 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\karri.anusha\\.cvlib\\object_detection\\yolo\\yolov3\\yolov3_classes.txt'

please assist

**Comment by andres-zartab** [comment]
Hi @anusha1110 ! As mentioned in the [pinned thread](https://www.coursera.org/learn/machine-learning-data-lifecycle-in-production/discussions/weeks/1/threads/qlCtYLHQEeuS9wo8jdZF7Q), our learner support and community-building activities have moved to Discourse. Please repost this there to get support from the course mentors and also your fellow learners. They will be happy to help you! [You can join it through this link](http://bit.ly/mlep-discourse). If you’re already a part of Discourse through the other DeepLearning.AI specializations (e.g. Deep Learning), then you can simply [log-in to your Discourse account](https://discourse.deeplearning.ai/login) and choose the category before posting. Hope to see you there!

I think this [thread](https://discourse.deeplearning.ai/t/course-1-week-1-connection-error/10884) addresses your question!
